ALTER PROC InsertNurse
@ECareTeamID INT,
@ENurseID INT
AS
--INSERT VALUES INTO NURSECARETEAM TBL
BEGIN TRY
INSERT into dbo.NurseCareTeamMembersTBL
(MemberID, CareTeamID)
VALUES
(@ENurseID, @ECareTeamID)
END TRY
BEGIN CATCH
;THROW
END CATCH